import { useState, useRef, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery, useMutation } from "@tanstack/react-query";
import {
  fetchPatient,
  fetchPatientProfile,
  runTrialMatch,
  sendChatMessage,
  type MatchResult,
  type ChatTurn,
  type Citation,
  type Patient,
} from "../lib/api";

// ── Referral packet helpers ──────────────────────────────────────────────────

interface TrialSection {
  nctId: string;
  title: string;
  text: string;
  verdict: "ELIGIBLE" | "PARTIAL" | "INELIGIBLE" | "UNKNOWN";
}

function parseTrialSections(response: string): TrialSection[] {
  const lines = response.split("\n");
  const sections: TrialSection[] = [];
  let current: { nctId: string; title: string; lines: string[] } | null = null;

  const flush = () => {
    if (!current) return;
    const text = current.lines.join("\n");
    let verdict: TrialSection["verdict"] = "UNKNOWN";
    if (/INELIGIBLE/.test(text)) verdict = "INELIGIBLE";
    else if (/PARTIAL/.test(text)) verdict = "PARTIAL";
    else if (/ELIGIBLE/.test(text)) verdict = "ELIGIBLE";
    sections.push({ nctId: current.nctId, title: current.title, text, verdict });
  };

  for (const line of lines) {
    const nctMatch = line.match(/NCT\d{8}/);
    if (nctMatch) {
      flush();
      current = {
        nctId: nctMatch[0],
        title: line.replace(/^#+\s*/, "").replace(/^\d+\.\s*/, "").trim(),
        lines: [line],
      };
    } else if (current) {
      current.lines.push(line);
    }
  }
  flush();
  return sections;
}

function extractSection(profile: string, header: string): string {
  const headerIdx = profile.indexOf(header);
  if (headerIdx === -1) return "";
  const after = profile.slice(headerIdx + header.length);
  return after
    .split("\n")
    .filter((l) => l.trim().startsWith("-"))
    .slice(0, 3)
    .map((l) => l.trim())
    .join("\n");
}

function buildReferralPacket(
  patient: Patient,
  section: TrialSection,
  profile: string
): string {
  const today = new Date().toISOString().slice(0, 10);
  const diagnosis = extractSection(profile, "Active Diagnoses / Cancer Conditions:");
  const labs = extractSection(profile, "Recent Laboratory Results");

  return [
    "CLINICAL TRIAL REFERRAL PACKET",
    `Generated: ${today}  |  Referring Clinician: Dr. Sarah Chen`,
    "",
    "PATIENT",
    `  Name:  ${patient.name}`,
    `  Age:   ${patient.age} yrs · ${patient.sex}`,
    `  DOB:   ${patient.dob}`,
    "",
    "PRIMARY DIAGNOSIS",
    diagnosis ? diagnosis.replace(/^/gm, "  ") : "  Not available",
    "",
    "KEY LABORATORY VALUES (most recent)",
    labs ? labs.replace(/^/gm, "  ") : "  Not available",
    "",
    "TRIAL",
    `  NCT ID:  ${section.nctId}`,
    `  Title:   ${section.title}`,
    `  Verdict: ${
      section.verdict === "ELIGIBLE"
        ? "ELIGIBLE ✅"
        : section.verdict === "PARTIAL"
        ? "PARTIAL ⚠️"
        : section.verdict
    }`,
    "",
    "ELIGIBILITY ASSESSMENT (AI-generated — not a medical determination)",
    section.text
      .split("\n")
      .map((l) => (l.trim() ? `  ${l}` : ""))
      .join("\n"),
    "",
    "SOURCE",
    `  https://clinicaltrials.gov/study/${section.nctId}`,
    "",
    "─".repeat(60),
    "This referral was generated by the Clinical Trial Matcher (AI decision-support tool).",
    "Final eligibility determination rests with the trial coordinator and investigator.",
  ].join("\n");
}

// Render agent response with basic formatting (bold, bullets)
function ReferralPacketModal({
  packetText,
  nctId,
  onClose,
}: {
  packetText: string;
  nctId: string;
  onClose: () => void;
}) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(packetText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
          <div>
            <h2 className="text-base font-semibold text-gray-900">Referral Packet</h2>
            <p className="text-xs text-gray-400 mt-0.5">{nctId}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors p-1"
            aria-label="Close"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Packet text */}
        <div className="overflow-y-auto flex-1 px-5 py-4">
          <pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap leading-relaxed bg-gray-50 rounded-lg p-4 border border-gray-200">
            {packetText}
          </pre>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-4 border-t border-gray-200 bg-gray-50 rounded-b-xl">
          <p className="text-xs text-gray-400">
            Paste into your email client or clinical portal.
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="text-sm text-gray-500 hover:text-gray-700 px-4 py-2 rounded-lg border border-gray-300 hover:bg-white transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg bg-blue-700 text-white hover:bg-blue-800 transition-colors"
            >
              {copied ? (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                  </svg>
                  Copy to Clipboard
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function AgentResponse({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <div className="space-y-1 text-sm text-gray-800 leading-relaxed">
      {lines.map((line, i) => {
        if (line.startsWith("### ") || line.startsWith("## ") || line.startsWith("# ")) {
          return (
            <p key={i} className="font-bold text-gray-900 mt-4 mb-1">
              {line.replace(/^#+\s*/, "")}
            </p>
          );
        }
        if (line.startsWith("**") && line.endsWith("**")) {
          return (
            <p key={i} className="font-semibold text-gray-900 mt-3">
              {line.replace(/\*\*/g, "")}
            </p>
          );
        }
        if (line.startsWith("- ") || line.startsWith("* ")) {
          return (
            <p key={i} className="pl-4">
              • {line.slice(2)}
            </p>
          );
        }
        if (line.trim() === "") return <div key={i} className="h-2" />;
        // Inline bold
        const parts = line.split(/(\*\*[^*]+\*\*)/g);
        return (
          <p key={i}>
            {parts.map((part, j) =>
              part.startsWith("**") && part.endsWith("**") ? (
                <strong key={j}>{part.replace(/\*\*/g, "")}</strong>
              ) : (
                <span key={j}>{part}</span>
              )
            )}
          </p>
        );
      })}
    </div>
  );
}

function VerdictBadge({ text }: { text: string }) {
  if (text.includes("ELIGIBLE ✅") || text.includes("✅")) {
    return <span className="bg-green-100 text-green-800 text-xs font-semibold px-2 py-0.5 rounded">ELIGIBLE ✅</span>;
  }
  if (text.includes("PARTIAL ⚠️") || text.includes("⚠️")) {
    return <span className="bg-yellow-100 text-yellow-800 text-xs font-semibold px-2 py-0.5 rounded">PARTIAL ⚠️</span>;
  }
  if (text.includes("INELIGIBLE ❌") || text.includes("❌")) {
    return <span className="bg-red-100 text-red-800 text-xs font-semibold px-2 py-0.5 rounded">INELIGIBLE ❌</span>;
  }
  return null;
}

export default function TrialMatchPage() {
  const { patientId } = useParams<{ patientId: string }>();
  const navigate = useNavigate();
  const [result, setResult] = useState<MatchResult | null>(null);
  const [threadId, setThreadId] = useState<string | null>(null);
  const [chatHistory, setChatHistory] = useState<ChatTurn[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [copiedNctId, setCopiedNctId] = useState<string | null>(null);
  const [openPacket, setOpenPacket] = useState<{ nctId: string; text: string } | null>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Scroll chat to bottom whenever history grows
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatHistory]);

  const { data: patient, isLoading: loadingPatient } = useQuery({
    queryKey: ["patient", patientId],
    queryFn: () => fetchPatient(patientId!),
    enabled: !!patientId,
  });

  const { data: profileData } = useQuery({
    queryKey: ["patientProfile", patientId],
    queryFn: () => fetchPatientProfile(patientId!),
    enabled: !!patientId && !!result,
    staleTime: Infinity,
  });

  function handleOpenPacket(section: TrialSection) {
    if (!patient || !profileData) return;
    const text = buildReferralPacket(patient, section, profileData.profile);
    setOpenPacket({ nctId: section.nctId, text });
  }

  function handleCopyPacket(section: TrialSection) {
    if (!patient || !profileData) return;
    const text = buildReferralPacket(patient, section, profileData.profile);
    navigator.clipboard.writeText(text).then(() => {
      setCopiedNctId(section.nctId);
      setTimeout(() => setCopiedNctId(null), 2500);
    });
  }

  const matchMutation = useMutation({
    mutationFn: () => runTrialMatch(patientId!),
    onSuccess: (data) => {
      setResult(data);
      setThreadId(data.thread_id);
      setChatHistory([]);
    },
  });

  const chatMutation = useMutation({
    mutationFn: (message: string) => sendChatMessage(threadId!, message),
    onSuccess: (data, message) => {
      setChatHistory((prev) => [
        ...prev,
        { role: "user", text: message, citations: [] },
        { role: "agent", text: data.response, citations: data.citations },
      ]);
      setChatInput("");
    },
  });

  function handleSendChat(e: React.FormEvent) {
    e.preventDefault();
    const msg = chatInput.trim();
    if (!msg || !threadId || chatMutation.isPending) return;
    chatMutation.mutate(msg);
  }

  if (loadingPatient) {
    return <div className="text-center py-16 text-gray-400">Loading patient…</div>;
  }

  return (
    <div>
      {/* Referral Packet Modal */}
      {openPacket && (
        <ReferralPacketModal
          packetText={openPacket.text}
          nctId={openPacket.nctId}
          onClose={() => setOpenPacket(null)}
        />
      )}
      {/* Back */}
      <button
        onClick={() => navigate("/patients")}
        className="text-sm text-blue-600 hover:underline mb-4 flex items-center gap-1"
      >
        ← Back to patients
      </button>

      {/* Patient identity */}
      {patient && (
        <div className="bg-white border border-gray-200 rounded-lg p-4 mb-5 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-gray-900">{patient.name}</h1>
            <p className="text-sm text-gray-500 mt-0.5">
              {patient.age} yrs · {patient.sex} · DOB: {patient.dob}
            </p>
          </div>
          <div className="text-xs text-gray-400 text-right">
            <div>Patient ID</div>
            <div className="font-mono text-gray-600">{patient.id}</div>
          </div>
        </div>
      )}

      {/* Run button */}
      {!result && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 text-center mb-6">
          <p className="text-gray-600 text-sm mb-4">
            The Foundry Agent will search the indexed ClinicalTrials.gov knowledge base
            and assess eligibility for recruiting oncology trials matching this patient's profile.
          </p>
          <button
            onClick={() => matchMutation.mutate()}
            disabled={matchMutation.isPending}
            className="bg-blue-700 text-white px-6 py-2.5 rounded-lg font-medium hover:bg-blue-800 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 mx-auto"
          >
            {matchMutation.isPending ? (
              <>
                <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                </svg>
                Running Foundry Agent…
              </>
            ) : (
              "🔍 Find Matching Trials"
            )}
          </button>
          {matchMutation.isPending && (
            <p className="text-xs text-gray-400 mt-3">
              Querying Foundry IQ knowledge base and assessing eligibility — this may take 15–30 seconds.
            </p>
          )}
        </div>
      )}

      {/* Error */}
      {matchMutation.isError && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded p-4 text-sm mb-4">
          {String(matchMutation.error)}
        </div>
      )}

      {/* Results */}
      {result && (
        <div>
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold">Trial Match Results</h2>
            <button
              onClick={() => { setResult(null); setThreadId(null); setChatHistory([]); matchMutation.reset(); }}
              className="text-xs text-gray-400 hover:text-gray-600 underline"
            >
              Run again
            </button>
          </div>

          {/* Agent response — split into per-trial sections when parseable */}
          {(() => {
            const sections = parseTrialSections(result.response);
            if (sections.length === 0) {
              // Fallback: render as single block
              return (
                <div className="bg-white border border-gray-200 rounded-lg p-5 mb-4">
                  <div className="flex items-center gap-2 mb-4 pb-3 border-b border-gray-100">
                    <span className="text-xs font-medium bg-blue-100 text-blue-700 px-2 py-0.5 rounded">
                      Foundry Agent · GPT-4o · Foundry IQ
                    </span>
                  </div>
                  <AgentResponse text={result.response} />
                </div>
              );
            }
            return (
              <div className="space-y-4 mb-4">
                {sections.map((section) => (
                  <div key={section.nctId} className="bg-white border border-gray-200 rounded-lg p-5">
                    <div className="flex items-center justify-between mb-3 pb-3 border-b border-gray-100">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-xs font-medium bg-blue-100 text-blue-700 px-2 py-0.5 rounded">
                          Foundry Agent · GPT-4o
                        </span>
                        <VerdictBadge text={section.text} />
                        <span className="text-xs font-mono text-gray-400">{section.nctId}</span>
                      </div>
                      {(section.verdict === "ELIGIBLE" || section.verdict === "PARTIAL") && (
                        <button
                          onClick={() => handleOpenPacket(section)}
                          disabled={!profileData}
                          title={!profileData ? "Loading patient profile…" : "View and copy referral packet"}
                          className="flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border transition-colors
                            disabled:opacity-40 disabled:cursor-not-allowed
                            hover:bg-gray-50 border-gray-300 text-gray-600"
                        >
                          <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                              d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                          </svg>
                          View Referral Packet
                        </button>
                      )}
                    </div>
                    <AgentResponse text={section.text} />
                  </div>
                ))}
              </div>
            );
          })()}

          {/* Citations */}
          {result.citations.length > 0 && (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
                Sources cited by Foundry IQ ({result.citations.length})
              </h3>
              <ol className="space-y-1.5">
                {result.citations.map((c, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="text-gray-400 text-xs mt-0.5 font-mono">[{i + 1}]</span>
                    {c.url ? (
                      <a
                        href={c.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline"
                      >
                        {c.title || c.url}
                      </a>
                    ) : (
                      <span className="text-gray-700">{c.title}</span>
                    )}
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* ── Trial Chat ──────────────────────────────────────────── */}
          <div className="mt-6">
            <div className="flex items-center gap-2 mb-3">
              <h2 className="text-base font-semibold text-gray-800">💬 Ask the Agent</h2>
              <span className="text-xs text-gray-400">
                The agent remembers the patient profile and all trial results above
              </span>
            </div>

            {/* Suggested prompts — shown before any chat turns */}
            {chatHistory.length === 0 && (
              <div className="flex flex-wrap gap-2 mb-4">
                {[
                  "Which trial has the fewest required visits?",
                  "Are there any trials near Boston?",
                  "What would change if the patient stopped current chemo?",
                  "Which ELIGIBLE trial has the earliest start date?",
                ].map((suggestion) => (
                  <button
                    key={suggestion}
                    onClick={() => { setChatInput(suggestion); }}
                    className="text-xs bg-blue-50 text-blue-700 border border-blue-200 rounded-full px-3 py-1 hover:bg-blue-100 transition-colors"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            )}

            {/* Chat history */}
            {chatHistory.length > 0 && (
              <div className="space-y-3 mb-4 max-h-[500px] overflow-y-auto pr-1">
                {chatHistory.map((turn, i) => (
                  <div key={i} className={`flex ${ turn.role === "user" ? "justify-end" : "justify-start"}`}>
                    {turn.role === "user" ? (
                      <div className="bg-blue-700 text-white text-sm rounded-2xl rounded-tr-sm px-4 py-2.5 max-w-[75%]">
                        {turn.text}
                      </div>
                    ) : (
                      <div className="bg-white border border-gray-200 rounded-2xl rounded-tl-sm px-4 py-3 max-w-[85%]">
                        <AgentResponse text={turn.text} />
                        {turn.citations.length > 0 && (
                          <div className="mt-2 pt-2 border-t border-gray-100">
                            <p className="text-xs text-gray-400 mb-1">Sources</p>
                            <ol className="space-y-0.5">
                              {turn.citations.map((c: Citation, j: number) => (
                                <li key={j} className="text-xs">
                                  <span className="text-gray-400 font-mono mr-1">[{j + 1}]</span>
                                  {c.url ? (
                                    <a href={c.url} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                                      {c.title || c.url}
                                    </a>
                                  ) : (
                                    <span className="text-gray-600">{c.title}</span>
                                  )}
                                </li>
                              ))}
                            </ol>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}
                {chatMutation.isPending && (
                  <div className="flex justify-start">
                    <div className="bg-white border border-gray-200 rounded-2xl rounded-tl-sm px-4 py-3 text-sm text-gray-400 flex items-center gap-2">
                      <svg className="animate-spin h-3 w-3" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                      </svg>
                      Thinking…
                    </div>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>
            )}

            {/* Chat error */}
            {chatMutation.isError && (
              <div className="bg-red-50 border border-red-200 text-red-700 rounded p-3 text-xs mb-3">
                {String(chatMutation.error)}
              </div>
            )}

            {/* Input */}
            <form onSubmit={handleSendChat} className="flex gap-2">
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask a follow-up question about these trials…"
                className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                disabled={chatMutation.isPending}
              />
              <button
                type="submit"
                disabled={!chatInput.trim() || chatMutation.isPending}
                className="bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-800 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Send
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
